# -*- coding: utf-8 -*-
"""Assignment-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xbGtzAehoz6zpOnDDhHHXAaHQfJf23DX
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
import datetime

data = pd.read_excel("Housing.xlsx",index_col=0)
data

"""#CLEANING DATA

1. Replace the missing values with appropriate approximations
"""

data['Acre']=data["Acre"].fillna(np.mean(data["Acre"]))
data['LandValue']=data["LandValue"].fillna(np.mean(data["LandValue"]))
data['BuildingValue']=data["BuildingValue"].fillna(np.mean(data["BuildingValue"]))
data['TotalValue']=data["TotalValue"].fillna(np.mean(data["TotalValue"]))
data['YearBuilt']=data["YearBuilt"].fillna(np.mean(data["YearBuilt"]))
data['Bedrooms']=data["Bedrooms"].fillna(np.mean(data["Bedrooms"]))
data['FullBath']=data["FullBath"].fillna(np.mean(data["FullBath"]))
data['HalfBath']=data["HalfBath"].fillna(np.mean(data["HalfBath"]))
data

"""2. Rename the columns to better suited names"""

data.rename(columns={"FullBath":"FullBathroom"},inplace=True)
data.rename(columns={"HalfBath":"HalfBathroom"},inplace=True)
data

"""3. Extract the month and year from the sale date."""

data['Year']=pd.DatetimeIndex(data['SaleDate']).year
data['Month']=pd.DatetimeIndex(data['SaleDate']).month
data['Day']=pd.DatetimeIndex(data['SaleDate']).day
data

"""4. Extract the pin number from the property address"""



"""#EDA

1. How has the price of properties changed over the years
"""

a = data.groupby('Year')['SalePrice'].count()
a

sns.barplot(x=a.index, y=a.values)

"""2. Does a specific month or span of months have the highest property prices?"""

b=data.groupby('Month')['SalePrice'].count()
b

sns.barplot(x=b.index, y=b.values)

plt.pie(b,labels=b.index)

"""3. For what purpose were the properties generally purchased?"""

c=data.groupby('LandUse')['SalePrice'].count()
c

sns.scatterplot(x='LandUse', y='SalePrice', data=data);

"""4. What is the average age of the properties?"""



"""5. Have the age of houses affected the price?"""



"""6. Have the number of rooms in the house affected the price?"""

data["TotalRooms"]=data['Bedrooms']+data['FullBathroom']+data['HalfBathroom']
data

d=data.groupby('TotalRooms')['SalePrice'].count()
d

sns.barplot(x=d.index,y=d.values)

sns.lineplot('TotalRooms','SalePrice',data=data);

"""7. Does the size of the property (no. of acres) have any influence in its price?"""

e=data.groupby('Acre')['SalePrice'].count()
e

sns.lineplot('Acre', 'SalePrice', data=data);

"""8. Are houses located in specific pin numbers expensive over the others?"""



"""9. How have house prices changed in the 21st centuary as supposed to 20th centuary."""

f=data.groupby('Year')['BuildingValue'].count()
f

g=data.groupby('YearBuilt')['LandValue'].count()
g

cent=data[data["YearBuilt"]>=1900]
cent